spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/saas_crm
    username: postgres
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6380

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
